"""Generates the Dart golden test that pins normaliseFoodName() to normalise().

The two implementations must agree exactly: Python writes
`foods.name_normalised` into the shipped database, and Dart computes the value
compared against it for both the search prefix tier and `food_cache` lookups.
A divergence throws no error — the cache simply never hits.

Rather than maintain the expectations by hand in two languages, they are
generated from the Python implementation and checked in.

    python gen_golden_test.py

Rerun this whenever normalise.py changes, and commit the result.
"""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from normalise import normalise  # noqa: E402

OUT = HERE.parent.parent / "test" / "core" / "food_name_test.dart"

CASES = [
    # Plain names pass through lowercased.
    "Molasses",
    "CHEERIOS",
    "Eggs",
    # Singularisation was removed precisely so these stay intact.
    "Couscous",
    "Molasses",
    # Punctuation becomes a single space; runs collapse.
    "Rice, white, long-grain",
    "Chicken, breast, boneless, skinless",
    "Beans, snap, green",
    "Yogurt, NFS",
    "2% milk",
    "Acerola, (west indian cherry)",
    "Agutuk, meat-caribou (Alaskan ice cream)",
    # Underscore is punctuation here, unlike Python's \\w.
    "chicken_breast",
    # Accents fold to their ASCII base.
    "Crème brûlée",
    "Mañana",
    "Smørrebrød",
    "Weißbier",
    "Crème fraîche",
    # Combining marks are kept, so Indic names survive as whole words.
    "चिकन बिरयानी",
    "चावल",
    "چکن بریانی",
    # Nothing searchable.
    "",
    "   ",
    "---",
    "!@#()",
]

HEADER = '''// GENERATED by tools/build_foods_db/gen_golden_test.py — do not edit by hand.
//
// Pins normaliseFoodName() to the Python normalise() that produced the
// name_normalised column in the shipped foods.sqlite. If these two ever
// disagree, food_cache silently stops hitting and the search prefix tier
// silently stops firing — no error, no crash, just a feature that quietly
// does nothing.
//
// Regenerate with:  python tools/build_foods_db/gen_golden_test.py

import 'package:calori/core/food_name.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('normaliseFoodName matches the Python builder', () {
'''

FOOTER = '''  });

  group('properties the database build relies on', () {
    test('is idempotent', () {
      for (final input in ['Crème brûlée', 'Rice, white', 'चिकन बिरयानी']) {
        final once = normaliseFoodName(input);
        expect(normaliseFoodName(once), once, reason: input);
      }
    });

    test('never leaves leading, trailing or doubled spaces', () {
      for (final input in ['  Rice,  white  ', '--Eggs--', '(Milk)']) {
        final result = normaliseFoodName(input);
        expect(result, result.trim());
        expect(result.contains('  '), isFalse, reason: input);
      }
    });

    test('keeps Indic combining marks as part of the word', () {
      // Without \\p{M} this splits into fragments and no Hindi food name can
      // ever be matched against the cache.
      expect(normaliseFoodName('बिरयानी').split(' ').length, 1);
    });
  });
}
'''


def dart_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$")
    )
    return f"'{escaped}'"


def main() -> int:
    seen: set[str] = set()
    lines: list[str] = []

    for case in CASES:
        if case in seen:
            continue
        seen.add(case)

        expected = normalise(case)
        label = case if case.strip() else repr(case)
        lines.append(
            f"    test({dart_string(label)}, () {{\n"
            f"      expect(normaliseFoodName({dart_string(case)}), "
            f"{dart_string(expected)});\n"
            f"    }});\n"
        )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(HEADER + "\n".join(lines) + FOOTER, encoding="utf-8")
    print(f"wrote {len(seen)} cases -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
