// GENERATED by tools/build_foods_db/gen_golden_test.py — do not edit by hand.
//
// Pins normaliseFoodName() to the Python normalise() that produced the
// name_normalised column in the shipped foods.sqlite. If these two ever
// disagree, food_cache silently stops hitting and the search prefix tier
// silently stops firing — no error, no crash, just a feature that quietly
// does nothing.
//
// Regenerate with:  python tools/build_foods_db/gen_golden_test.py

import 'package:calori/core/food_name.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('normaliseFoodName matches the Python builder', () {
    test('Molasses', () {
      expect(normaliseFoodName('Molasses'), 'molasses');
    });

    test('CHEERIOS', () {
      expect(normaliseFoodName('CHEERIOS'), 'cheerios');
    });

    test('Eggs', () {
      expect(normaliseFoodName('Eggs'), 'eggs');
    });

    test('Couscous', () {
      expect(normaliseFoodName('Couscous'), 'couscous');
    });

    test('Rice, white, long-grain', () {
      expect(normaliseFoodName('Rice, white, long-grain'), 'rice white long grain');
    });

    test('Chicken, breast, boneless, skinless', () {
      expect(normaliseFoodName('Chicken, breast, boneless, skinless'), 'chicken breast boneless skinless');
    });

    test('Beans, snap, green', () {
      expect(normaliseFoodName('Beans, snap, green'), 'beans snap green');
    });

    test('Yogurt, NFS', () {
      expect(normaliseFoodName('Yogurt, NFS'), 'yogurt nfs');
    });

    test('2% milk', () {
      expect(normaliseFoodName('2% milk'), '2 milk');
    });

    test('Acerola, (west indian cherry)', () {
      expect(normaliseFoodName('Acerola, (west indian cherry)'), 'acerola west indian cherry');
    });

    test('Agutuk, meat-caribou (Alaskan ice cream)', () {
      expect(normaliseFoodName('Agutuk, meat-caribou (Alaskan ice cream)'), 'agutuk meat caribou alaskan ice cream');
    });

    test('chicken_breast', () {
      expect(normaliseFoodName('chicken_breast'), 'chicken breast');
    });

    test('Crème brûlée', () {
      expect(normaliseFoodName('Crème brûlée'), 'creme brulee');
    });

    test('Mañana', () {
      expect(normaliseFoodName('Mañana'), 'manana');
    });

    test('Smørrebrød', () {
      expect(normaliseFoodName('Smørrebrød'), 'smørrebrød');
    });

    test('Weißbier', () {
      expect(normaliseFoodName('Weißbier'), 'weißbier');
    });

    test('Crème fraîche', () {
      expect(normaliseFoodName('Crème fraîche'), 'creme fraiche');
    });

    test('चिकन बिरयानी', () {
      expect(normaliseFoodName('चिकन बिरयानी'), 'चिकन बिरयानी');
    });

    test('चावल', () {
      expect(normaliseFoodName('चावल'), 'चावल');
    });

    test('چکن بریانی', () {
      expect(normaliseFoodName('چکن بریانی'), 'چکن بریانی');
    });

    test('\'\'', () {
      expect(normaliseFoodName(''), '');
    });

    test('\'   \'', () {
      expect(normaliseFoodName('   '), '');
    });

    test('---', () {
      expect(normaliseFoodName('---'), '');
    });

    test('!@#()', () {
      expect(normaliseFoodName('!@#()'), '');
    });
  });

  group('properties the database build relies on', () {
    test('is idempotent', () {
      for (final input in ['Crème brûlée', 'Rice, white', 'चिकन बिरयानी']) {
        final once = normaliseFoodName(input);
        expect(normaliseFoodName(once), once, reason: input);
      }
    });

    test('never leaves leading, trailing or doubled spaces', () {
      for (final input in ['  Rice,  white  ', '--Eggs--', '(Milk)']) {
        final result = normaliseFoodName(input);
        expect(result, result.trim());
        expect(result.contains('  '), isFalse, reason: input);
      }
    });

    test('keeps Indic combining marks as part of the word', () {
      // Without \p{M} this splits into fragments and no Hindi food name can
      // ever be matched against the cache.
      expect(normaliseFoodName('बिरयानी').split(' ').length, 1);
    });
  });
}
